branch-defaults:
  default:
    environment: Torium-api
environment-defaults:
  Torium-api:
    branch: null
    repository: null
global:
  application_name: Torium-api
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: private
  sc: null
  workspace_type: Application
